// 253 countries
const countries = [
     { value: "Afghanistan-AF-93", name: "Afghanistan", code: "AF", phone: 93 },
     { value: "Aland Islands-AX-358", name: "Aland Islands", code: "AX", phone: 358 },
     { value: "Albania-AL-355", name: "Albania", code: "AL", phone: 355 },
     { value: "Algeria-DZ-213", name: "Algeria", code: "DZ", phone: 213 },
     { value: "American Samoa-AS-1684", name: "American Samoa", code: "AS", phone: 1684 },
     { value: "Andorra-AD-376", name: "Andorra", code: "AD", phone: 376 },
     { value: "Angola-AO-244", name: "Angola", code: "AO", phone: 244 },
     { value: "Anguilla-AI-1264", name: "Anguilla", code: "AI", phone: 1264 },
     { value: "Antarctica-AQ-672", name: "Antarctica", code: "AQ", phone: 672 },
     { value: "Antigua and Barbuda-AG-1268", name: "Antigua and Barbuda", code: "AG", phone: 1268 },
     { value: "Argentina-AR-54", name: "Argentina", code: "AR", phone: 54 },
     { value: "Armenia-AM-374", name: "Armenia", code: "AM", phone: 374 },
     { value: "Aruba-AW-297", name: "Aruba", code: "AW", phone: 297 },
     { value: "Australia-AU-61", name: "Australia", code: "AU", phone: 61 },
     { value: "Austria-AT-43", name: "Austria", code: "AT", phone: 43 },
     { value: "Azerbaijan-AZ-994", name: "Azerbaijan", code: "AZ", phone: 994 },
     { value: "Bahamas-BS-1242", name: "Bahamas", code: "BS", phone: 1242 },
     { value: "Bahrain-BH-973", name: "Bahrain", code: "BH", phone: 973 },
     { value: "Bangladesh-BD-880", name: "Bangladesh", code: "BD", phone: 880 },
     { value: "Barbados-BB-1246", name: "Barbados", code: "BB", phone: 1246 },
     { value: "Belarus-BY-375", name: "Belarus", code: "BY", phone: 375 },
     { value: "Belgium-BE-32", name: "Belgium", code: "BE", phone: 32 },
     { value: "Belize-BZ-501", name: "Belize", code: "BZ", phone: 501 },
     { value: "Benin-BJ-229", name: "Benin", code: "BJ", phone: 229 },
     { value: "Bermuda-BM-1441", name: "Bermuda", code: "BM", phone: 1441 },
     { value: "Bhutan-BT-975", name: "Bhutan", code: "BT", phone: 975 },
     { value: "Bolivia-BO-591", name: "Bolivia", code: "BO", phone: 591 },
     { value: "Bonaire, Sint Eustatius and Saba-BQ-599", name: "Bonaire, Sint Eustatius and Saba", code: "BQ", phone: 599 },
     { value: "Bosnia and Herzegovina-BA-387", name: "Bosnia and Herzegovina", code: "BA", phone: 387 },
     { value: "Botswana-BW-267", name: "Botswana", code: "BW", phone: 267 },
     { value: "Bouvet Island-BV-55", name: "Bouvet Island", code: "BV", phone: 55 },
     { value: "Brazil-BR-55", name: "Brazil", code: "BR", phone: 55 },
     { value: "British Indian Ocean Territory-IO-246", name: "British Indian Ocean Territory", code: "IO", phone: 246 },
     { value: "Brunei Darussalam-BN-673", name: "Brunei Darussalam", code: "BN", phone: 673 },
     { value: "Bulgaria-BG-359", name: "Bulgaria", code: "BG", phone: 359 },
     { value: "Burkina Faso-BF-226", name: "Burkina Faso", code: "BF", phone: 226 },
     { value: "Burundi-BI-257", name: "Burundi", code: "BI", phone: 257 },
     { value: "Cambodia-KH-855", name: "Cambodia", code: "KH", phone: 855 },
     { value: "Cameroon-CM-237", name: "Cameroon", code: "CM", phone: 237 },
     { value: "Canada-CA-1", name: "Canada", code: "CA", phone: 1 },
     { value: "Cape Verde-CV-238", name: "Cape Verde", code: "CV", phone: 238 },
     { value: "Cayman Islands-KY-1345", name: "Cayman Islands", code: "KY", phone: 1345 },
     { value: "Central African Republic-CF-236", name: "Central African Republic", code: "CF", phone: 236 },
     { value: "Chad-TD-235", name: "Chad", code: "TD", phone: 235 },
     { value: "Chile-CL-56", name: "Chile", code: "CL", phone: 56 },
     { value: "China-CN-86", name: "China", code: "CN", phone: 86 },
     { value: "Christmas Island-CX-61", name: "Christmas Island", code: "CX", phone: 61 },
     { value: "Cocos (Keeling) Islands-CC-672", name: "Cocos (Keeling) Islands", code: "CC", phone: 672 },
     { value: "Colombia-CO-57", name: "Colombia", code: "CO", phone: 57 },
     { value: "Comoros-KM-269", name: "Comoros", code: "KM", phone: 269 },
     { value: "Congo-CG-242", name: "Congo", code: "CG", phone: 242 },
     { value: "Congo, Democratic Republic of the Congo-CD-242", name: "Congo, Democratic Republic of the Congo", code: "CD", phone: 242 },
     { value: "Cook Islands-CK-682", name: "Cook Islands", code: "CK", phone: 682 },
     { value: "Costa Rica-CR-506", name: "Costa Rica", code: "CR", phone: 506 },
     { value: "Cote D'Ivoire-CI-225", name: "Cote D'Ivoire", code: "CI", phone: 225 },
     { value: "Croatia-HR-385", name: "Croatia", code: "HR", phone: 385 },
     { value: "Cuba-CU-53", name: "Cuba", code: "CU", phone: 53 },
     { value: "Curacao-CW-599", name: "Curacao", code: "CW", phone: 599 },
     { value: "Cyprus-CY-357", name: "Cyprus", code: "CY", phone: 357 },
     { value: "Czech Republic-CZ-420", name: "Czech Republic", code: "CZ", phone: 420 },
     { value: "Denmark-DK-45", name: "Denmark", code: "DK", phone: 45 },
     { value: "Djibouti-DJ-253", name: "Djibouti", code: "DJ", phone: 253 },
     { value: "Dominica-DM-1767", name: "Dominica", code: "DM", phone: 1767 },
     { value: "Dominican Republic-DO-1809", name: "Dominican Republic", code: "DO", phone: 1809 },
     { value: "Ecuador-EC-593", name: "Ecuador", code: "EC", phone: 593 },
     { value: "Egypt-EG-20", name: "Egypt", code: "EG", phone: 20 },
     { value: "El Salvador-SV-503", name: "El Salvador", code: "SV", phone: 503 },
     { value: "Equatorial Guinea-GQ-240", name: "Equatorial Guinea", code: "GQ", phone: 240 },
     { value: "Eritrea-ER-291", name: "Eritrea", code: "ER", phone: 291 },
     { value: "Estonia-EE-372", name: "Estonia", code: "EE", phone: 372 },
     { value: "Ethiopia-ET-251", name: "Ethiopia", code: "ET", phone: 251 },
     { value: "Falkland Islands (Malvinas)-FK-500", name: "Falkland Islands (Malvinas)", code: "FK", phone: 500 },
     { value: "Faroe Islands-FO-298", name: "Faroe Islands", code: "FO", phone: 298 },
     { value: "Fiji-FJ-679", name: "Fiji", code: "FJ", phone: 679 },
     { value: "Finland-FI-358", name: "Finland", code: "FI", phone: 358 },
     { value: "France-FR-33", name: "France", code: "FR", phone: 33 },
     { value: "French Guiana-GF-594", name: "French Guiana", code: "GF", phone: 594 },
     { value: "French Polynesia-PF-689", name: "French Polynesia", code: "PF", phone: 689 },
     { value: "French Southern Territories-TF-262", name: "French Southern Territories", code: "TF", phone: 262 },
     { value: "Gabon-GA-241", name: "Gabon", code: "GA", phone: 241 },
     { value: "Gambia-GM-220", name: "Gambia", code: "GM", phone: 220 },
     { value: "Georgia-GE-995", name: "Georgia", code: "GE", phone: 995 },
     { value: "Germany-DE-49", name: "Germany", code: "DE", phone: 49 },
     { value: "Ghana-GH-233", name: "Ghana", code: "GH", phone: 233 },
     { value: "Gibraltar-GI-350", name: "Gibraltar", code: "GI", phone: 350 },
     { value: "Greece-GR-30", name: "Greece", code: "GR", phone: 30 },
     { value: "Greenland-GL-299", name: "Greenland", code: "GL", phone: 299 },
     { value: "Grenada-GD-1473", name: "Grenada", code: "GD", phone: 1473 },
     { value: "Guadeloupe-GP-590", name: "Guadeloupe", code: "GP", phone: 590 },
     { value: "Guam-GU-1671", name: "Guam", code: "GU", phone: 1671 },
     { value: "Guatemala-GT-502", name: "Guatemala", code: "GT", phone: 502 },
     { value: "Guernsey-GG-44", name: "Guernsey", code: "GG", phone: 44 },
     { value: "Guinea-GN-224", name: "Guinea", code: "GN", phone: 224 },
     { value: "Guinea-Bissau-GW-245", name: "Guinea-Bissau", code: "GW", phone: 245 },
     { value: "Guyana-GY-592", name: "Guyana", code: "GY", phone: 592 },
     { value: "Haiti-HT-509", name: "Haiti", code: "HT", phone: 509 },
     { value: "Heard Island and McDonald Islands-HM-0", name: "Heard Island and McDonald Islands", code: "HM", phone: 0 },
     { value: "Holy See (Vatican City State)-VA-39", name: "Holy See (Vatican City State)", code: "VA", phone: 39 },
     { value: "Honduras-HN-504", name: "Honduras", code: "HN", phone: 504 },
     { value: "Hong Kong-HK-852", name: "Hong Kong", code: "HK", phone: 852 },
     { value: "Hungary-HU-36", name: "Hungary", code: "HU", phone: 36 },
     { value: "Iceland-IS-354", name: "Iceland", code: "IS", phone: 354 },
     { value: "India-IN-91", name: "India", code: "IN", phone: 91 },
     { value: "Indonesia-ID-62", name: "Indonesia", code: "ID", phone: 62 },
     { value: "Iran, Islamic Republic of-IR-98", name: "Iran, Islamic Republic of", code: "IR", phone: 98 },
     { value: "Iraq-IQ-964", name: "Iraq", code: "IQ", phone: 964 },
     { value: "Ireland-IE-353", name: "Ireland", code: "IE", phone: 353 },
     { value: "Isle of Man-IM-44", name: "Isle of Man", code: "IM", phone: 44 },
     { value: "Israel-IL-972", name: "Israel", code: "IL", phone: 972 },
     { value: "Italy-IT-39", name: "Italy", code: "IT", phone: 39 },
     { value: "Jamaica-JM-1876", name: "Jamaica", code: "JM", phone: 1876 },
     { value: "Japan-JP-81", name: "Japan", code: "JP", phone: 81 },
     { value: "Jersey-JE-44", name: "Jersey", code: "JE", phone: 44 },
     { value: "Jordan-JO-962", name: "Jordan", code: "JO", phone: 962 },
     { value: "Kazakhstan-KZ-7", name: "Kazakhstan", code: "KZ", phone: 7 },
     { value: "Kenya-KE-254", name: "Kenya", code: "KE", phone: 254 },
     { value: "Kiribati-KI-686", name: "Kiribati", code: "KI", phone: 686 },
     { value: "Korea, Democratic People's Republic of-KP-850", name: "Korea, Democratic People's Republic of", code: "KP", phone: 850 },
     { value: "Korea, Republic of-KR-82", name: "Korea, Republic of", code: "KR", phone: 82 },
     { value: "Kosovo-XK-383", name: "Kosovo", code: "XK", phone: 383 },
     { value: "Kuwait-KW-965", name: "Kuwait", code: "KW", phone: 965 },
     { value: "Kyrgyzstan-KG-996", name: "Kyrgyzstan", code: "KG", phone: 996 },
     { value: "Lao People's Democratic Republic-LA-856", name: "Lao People's Democratic Republic", code: "LA", phone: 856 },
     { value: "Latvia-LV-371", name: "Latvia", code: "LV", phone: 371 },
     { value: "Lebanon-LB-961", name: "Lebanon", code: "LB", phone: 961 },
     { value: "Lesotho-LS-266", name: "Lesotho", code: "LS", phone: 266 },
     { value: "Liberia-LR-231", name: "Liberia", code: "LR", phone: 231 },
     { value: "Libyan Arab Jamahiriya-LY-218", name: "Libyan Arab Jamahiriya", code: "LY", phone: 218 },
     { value: "Liechtenstein-LI-423", name: "Liechtenstein", code: "LI", phone: 423 },
     { value: "Lithuania-LT-370", name: "Lithuania", code: "LT", phone: 370 },
     { value: "Luxembourg-LU-352", name: "Luxembourg", code: "LU", phone: 352 },
     { value: "Macao-MO-853", name: "Macao", code: "MO", phone: 853 },
     { value: "Macedonia, the Former Yugoslav Republic of-MK-389", name: "Macedonia, the Former Yugoslav Republic of", code: "MK", phone: 389 },
     { value: "Madagascar-MG-261", name: "Madagascar", code: "MG", phone: 261 },
     { value: "Malawi-MW-265", name: "Malawi", code: "MW", phone: 265 },
     { value: "Malaysia-MY-60", name: "Malaysia", code: "MY", phone: 60 },
     { value: "Maldives-MV-960", name: "Maldives", code: "MV", phone: 960 },
     { value: "Mali-ML-223", name: "Mali", code: "ML", phone: 223 },
     { value: "Malta-MT-356", name: "Malta", code: "MT", phone: 356 },
     { value: "Marshall Islands-MH-692", name: "Marshall Islands", code: "MH", phone: 692 },
     { value: "Martinique-MQ-596", name: "Martinique", code: "MQ", phone: 596 },
     { value: "Mauritania-MR-222", name: "Mauritania", code: "MR", phone: 222 },
     { value: "Mauritius-MU-230", name: "Mauritius", code: "MU", phone: 230 },
     { value: "Mayotte-YT-262", name: "Mayotte", code: "YT", phone: 262 },
     { value: "Mexico-MX-52", name: "Mexico", code: "MX", phone: 52 },
     { value: "Micronesia, Federated States of-FM-691", name: "Micronesia, Federated States of", code: "FM", phone: 691 },
     { value: "Moldova, Republic of-MD-373", name: "Moldova, Republic of", code: "MD", phone: 373 },
     { value: "Monaco-MC-377", name: "Monaco", code: "MC", phone: 377 },
     { value: "Mongolia-MN-976", name: "Mongolia", code: "MN", phone: 976 },
     { value: "Montenegro-ME-382", name: "Montenegro", code: "ME", phone: 382 },
     { value: "Montserrat-MS-1664", name: "Montserrat", code: "MS", phone: 1664 },
     { value: "Morocco-MA-212", name: "Morocco", code: "MA", phone: 212 },
     { value: "Mozambique-MZ-258", name: "Mozambique", code: "MZ", phone: 258 },
     { value: "Myanmar-MM-95", name: "Myanmar", code: "MM", phone: 95 },
     { value: "Namibia-NA-264", name: "Namibia", code: "NA", phone: 264 },
     { value: "Nauru-NR-674", name: "Nauru", code: "NR", phone: 674 },
     { value: "Nepal-NP-977", name: "Nepal", code: "NP", phone: 977 },
     { value: "Netherlands-NL-31", name: "Netherlands", code: "NL", phone: 31 },
     { value: "Netherlands Antilles-AN-599", name: "Netherlands Antilles", code: "AN", phone: 599 },
     { value: "New Caledonia-NC-687", name: "New Caledonia", code: "NC", phone: 687 },
     { value: "New Zealand-NZ-64", name: "New Zealand", code: "NZ", phone: 64 },
     { value: "Nicaragua-NI-505", name: "Nicaragua", code: "NI", phone: 505 },
     { value: "Niger-NE-227", name: "Niger", code: "NE", phone: 227 },
     { value: "Nigeria-NG-234", name: "Nigeria", code: "NG", phone: 234 },
     { value: "Niue-NU-683", name: "Niue", code: "NU", phone: 683 },
     { value: "Norfolk Island-NF-672", name: "Norfolk Island", code: "NF", phone: 672 },
     { value: "Northern Mariana Islands-MP-1670", name: "Northern Mariana Islands", code: "MP", phone: 1670 },
     { value: "Norway-NO-47", name: "Norway", code: "NO", phone: 47 },
     { value: "Oman-OM-968", name: "Oman", code: "OM", phone: 968 },
     { value: "Pakistan-PK-92", name: "Pakistan", code: "PK", phone: 92 },
     { value: "Palau-PW-680", name: "Palau", code: "PW", phone: 680 },
     { value: "Palestinian Territory, Occupied-PS-970", name: "Palestinian Territory, Occupied", code: "PS", phone: 970 },
     { value: "Panama-PA-507", name: "Panama", code: "PA", phone: 507 },
     { value: "Papua New Guinea-PG-675", name: "Papua New Guinea", code: "PG", phone: 675 },
     { value: "Paraguay-PY-595", name: "Paraguay", code: "PY", phone: 595 },
     { value: "Peru-PE-51", name: "Peru", code: "PE", phone: 51 },
     { value: "Philippines-PH-63", name: "Philippines", code: "PH", phone: 63 },
     { value: "Pitcairn-PN-64", name: "Pitcairn", code: "PN", phone: 64 },
     { value: "Poland-PL-48", name: "Poland", code: "PL", phone: 48 },
     { value: "Portugal-PT-351", name: "Portugal", code: "PT", phone: 351 },
     { value: "Puerto Rico-PR-1787", name: "Puerto Rico", code: "PR", phone: 1787 },
     { value: "Qatar-QA-974", name: "Qatar", code: "QA", phone: 974 },
     { value: "Reunion-RE-262", name: "Reunion", code: "RE", phone: 262 },
     { value: "Romania-RO-40", name: "Romania", code: "RO", phone: 40 },
     { value: "Russian Federation-RU-7", name: "Russian Federation", code: "RU", phone: 7 },
     { value: "Rwanda-RW-250", name: "Rwanda", code: "RW", phone: 250 },
     { value: "Saint Barthelemy-BL-590", name: "Saint Barthelemy", code: "BL", phone: 590 },
     { value: "Saint Helena-SH-290", name: "Saint Helena", code: "SH", phone: 290 },
     { value: "Saint Kitts and Nevis-KN-1869", name: "Saint Kitts and Nevis", code: "KN", phone: 1869 },
     { value: "Saint Lucia-LC-1758", name: "Saint Lucia", code: "LC", phone: 1758 },
     { value: "Saint Martin-MF-590", name: "Saint Martin", code: "MF", phone: 590 },
     { value: "Saint Pierre and Miquelon-PM-508", name: "Saint Pierre and Miquelon", code: "PM", phone: 508 },
     { value: "Saint Vincent and the Grenadines-VC-1784", name: "Saint Vincent and the Grenadines", code: "VC", phone: 1784 },
     { value: "Samoa-WS-684", name: "Samoa", code: "WS", phone: 684 },
     { value: "San Marino-SM-378", name: "San Marino", code: "SM", phone: 378 },
     { value: "Sao Tome and Principe-ST-239", name: "Sao Tome and Principe", code: "ST", phone: 239 },
     { value: "Saudi Arabia-SA-966", name: "Saudi Arabia", code: "SA", phone: 966 },
     { value: "Senegal-SN-221", name: "Senegal", code: "SN", phone: 221 },
     { value: "Serbia-RS-381", name: "Serbia", code: "RS", phone: 381 },
     { value: "Serbia and Montenegro-CS-381", name: "Serbia and Montenegro", code: "CS", phone: 381 },
     { value: "Seychelles-SC-248", name: "Seychelles", code: "SC", phone: 248 },
     { value: "Sierra Leone-SL-232", name: "Sierra Leone", code: "SL", phone: 232 },
     { value: "Singapore-SG-65", name: "Singapore", code: "SG", phone: 65 },
     { value: "St Martin-SX-721", name: "St Martin", code: "SX", phone: 721 },
     { value: "Slovakia-SK-421", name: "Slovakia", code: "SK", phone: 421 },
     { value: "Slovenia-SI-386", name: "Slovenia", code: "SI", phone: 386 },
     { value: "Solomon Islands-SB-677", name: "Solomon Islands", code: "SB", phone: 677 },
     { value: "Somalia-SO-252", name: "Somalia", code: "SO", phone: 252 },
     { value: "South Africa-ZA-27", name: "South Africa", code: "ZA", phone: 27 },
     { value: "South Georgia and the South Sandwich Islands-GS-500", name: "South Georgia and the South Sandwich Islands", code: "GS", phone: 500 },
     { value: "South Sudan-SS-211", name: "South Sudan", code: "SS", phone: 211 },
     { value: "Spain-ES-34", name: "Spain", code: "ES", phone: 34 },
     { value: "Sri Lanka-LK-94", name: "Sri Lanka", code: "LK", phone: 94 },
     { value: "Sudan-SD-249", name: "Sudan", code: "SD", phone: 249 },
     { value: "Suriname-SR-597", name: "Suriname", code: "SR", phone: 597 },
     { value: "Svalbard and Jan Mayen-SJ-47", name: "Svalbard and Jan Mayen", code: "SJ", phone: 47 },
     { value: "Swaziland-SZ-268", name: "Swaziland", code: "SZ", phone: 268 },
     { value: "Sweden-SE-46", name: "Sweden", code: "SE", phone: 46 },
     { value: "Switzerland-CH-41", name: "Switzerland", code: "CH", phone: 41 },
     { value: "Syrian Arab Republic-SY-963", name: "Syrian Arab Republic", code: "SY", phone: 963 },
     { value: "Taiwan, Province of China-TW-886", name: "Taiwan, Province of China", code: "TW", phone: 886 },
     { value: "Tajikistan-TJ-992", name: "Tajikistan", code: "TJ", phone: 992 },
     { value: "Tanzania, United Republic of-TZ-255", name: "Tanzania, United Republic of", code: "TZ", phone: 255 },
     { value: "Thailand-TH-66", name: "Thailand", code: "TH", phone: 66 },
     { value: "Timor-Leste-TL-670", name: "Timor-Leste", code: "TL", phone: 670 },
     { value: "Togo-TG-228", name: "Togo", code: "TG", phone: 228 },
     { value: "Tokelau-TK-690", name: "Tokelau", code: "TK", phone: 690 },
     { value: "Tonga-TO-676", name: "Tonga", code: "TO", phone: 676 },
     { value: "Trinidad and Tobago-TT-1868", name: "Trinidad and Tobago", code: "TT", phone: 1868 },
     { value: "Tunisia-TN-216", name: "Tunisia", code: "TN", phone: 216 },
     { value: "Turkey-TR-90", name: "Turkey", code: "TR", phone: 90 },
     { value: "Turkmenistan-TM-7370", name: "Turkmenistan", code: "TM", phone: 7370 },
     { value: "Turks and Caicos Islands-TC-1649", name: "Turks and Caicos Islands", code: "TC", phone: 1649 },
     { value: "Tuvalu-TV-688", name: "Tuvalu", code: "TV", phone: 688 },
     { value: "Uganda-UG-256", name: "Uganda", code: "UG", phone: 256 },
     { value: "Ukraine-UA-380", name: "Ukraine", code: "UA", phone: 380 },
     { value: "United Arab Emirates-AE-971", name: "United Arab Emirates", code: "AE", phone: 971 },
     { value: "United Kingdom-GB-44", name: "United Kingdom", code: "GB", phone: 44 },
     { value: "United States-US-1", name: "United States", code: "US", phone: 1 },
     { value: "United States Minor Outlying Islands-UM-1", name: "United States Minor Outlying Islands", code: "UM", phone: 1 },
     { value: "Uruguay-UY-598", name: "Uruguay", code: "UY", phone: 598 },
     { value: "Uzbekistan-UZ-998", name: "Uzbekistan", code: "UZ", phone: 998 },
     { value: "Vanuatu-VU-678", name: "Vanuatu", code: "VU", phone: 678 },
     { value: "Venezuela-VE-58", name: "Venezuela", code: "VE", phone: 58 },
     { value: "Viet Nam-VN-84", name: "Viet Nam", code: "VN", phone: 84 },
     { value: "Virgin Islands, British-VG-1284", name: "Virgin Islands, British", code: "VG", phone: 1284 },
     { value: "Virgin Islands, U.s.-VI-1340", name: "Virgin Islands, U.s.", code: "VI", phone: 1340 },
     { value: "Wallis and Futuna-WF-681", name: "Wallis and Futuna", code: "WF", phone: 681 },
     { value: "Western Sahara-EH-212", name: "Western Sahara", code: "EH", phone: 212 },
     { value: "Yemen-YE-967", name: "Yemen", code: "YE", phone: 967 },
     { value: "Zambia-ZM-260", name: "Zambia", code: "ZM", phone: 260 },
     { value: "Zimbabwe-ZW-263", name: "Zimbabwe", code: "ZW", phone: 263 },

],

    selected_box = document.querySelector('.options'),
    search_box = document.querySelector('.search-box'),
    input_box = document.querySelector('input[type="tel"]'),
    selected_option = document.querySelector('.selected-option div');

let options = null;

for (country of countries) {
    const option = `
    <li class="option">
        <div>
            <span class="iconify" data-icon="flag:${country.code.toLowerCase()}-4x3"></span>
            <span class="country-name">${country.name}</span>
        </div>
        <strong>+${country.phone}</strong>
    </li> `;

    selected_box.querySelector('ol').insertAdjacentHTML('beforeend', option);
    options = document.querySelectorAll('.option');
}

function selectOption() {
    console.log(this);
    const icon = this.querySelector('.iconify').cloneNode(true),
        phone_code = this.querySelector('strong').cloneNode(true);

    selected_option.innerHTML = '';
    selected_option.append(icon, phone_code,);

    input_box.value = phone_code.innerText;

    selected_box.classList.remove('active');
    selected_option.classList.remove('active');

    search_box.value = '';
    selected_box.querySelectorAll('.hide').forEach(el => el.classList.remove('hide'));
}

function searchCountry() {
    let search_query = search_box.value.toLowerCase();
    for (option of options) {
        let is_matched = option.querySelector('.country-name').innerText.toLowerCase().includes(search_query);
        option.classList.toggle('hide', !is_matched)
    }
}


selected_option.addEventListener('click', () => {
    selected_box.classList.toggle('active');
    selected_option.classList.toggle('active');
})

options.forEach(option => option.addEventListener('click', selectOption));
search_box.addEventListener('input', searchCountry);
